#!/bin/bash

# Get the list of staged files
files=$(git diff --name-only --cached --diff-filter=ACM | grep '\.scala$')

echo "Found the following Scala files in the diff:"
echo "$files"

# Exit if there are no staged Scala files
if [[ -z "$files" ]]; then
    exit 0
fi

# Run scalafmt on each staged file
sbt scalafmt "scalafmtFilter=diff-dirty"

# Add the formatted files to the staging area
git add $files

# Print a message
echo "Formatted the following files:"
echo "$files"

exit 0
